name: Kernel Build

on:
  workflow_dispatch:
    inputs:
      hide_warnings:
        description: 'Silence warnings?'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install System Dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y wget xz-utils make bc bison flex libssl-dev libelf-dev git libtinfo5 libncurses5 libxml2

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Collect diagnostics
      run: bash diagnose.sh

    - name: Run Build Script
      run: |
        chmod +x build.sh
        if [ "${{ inputs.hide_warnings }}" = "true" ]; then
          ./build.sh -w
        else
          ./build.sh
        fi

    - name: Cache Clang
      uses: actions/cache@v4
      with:
        path: ~/toolchains/clang-r383902b1
        key: clang-r383902b1

    - name: Check if kernel image exists
      run: |
        if [ ! -f "out/arch/arm64/boot/Image.gz-dtb" ]; then
        echo "Error: Image.gz not found! Build failed."
        exit 1
        fi
        echo "Image.gz found, build successful."

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trinket-kernel
        path: |
          out/arch/arm64/boot/Image.gz-dtb
          out/arch/arm64/boot/dtbo.img
          out/arch/arm64/boot/dtb
        retention-days: 7